"""
Constants for NovaDB.

This module provides standard definitions for:
- Residue types (amino acids, nucleotides)
- Atom definitions per residue
- Element properties
- Bond types
- Token vocabulary
- AlphaFold3-specific constants (glycans, ions, exclusions)
"""

from novadb.constants.atoms import (
    CHI_ANGLES_ATOMS,
    CHI_ANGLES_MASK,
    DNA_ATOMS,
    DNA_BACKBONE_ATOMS,
    DNA_FRAME_ATOMS,
    MAX_ATOMS_PER_TOKEN,
    MAX_DNA_ATOMS,
    MAX_PROTEIN_ATOMS,
    MAX_RNA_ATOMS,
    PROTEIN_BACKBONE_ATOMS,
    PROTEIN_FRAME_ATOMS,
    RESIDUE_ATOMS,
    RESIDUE_ATOM_INDEX,
    RNA_ATOMS,
    RNA_BACKBONE_ATOMS,
    RNA_FRAME_ATOMS,
)
from novadb.constants.bonds import (
    BOND_LENGTH_TOLERANCE,
    BOND_TYPE_ORDER,
    COVALENT_BOND_TOLERANCE,
    DNA_BACKBONE_BONDS,
    NUM_BOND_TYPES,
    PEPTIDE_BOND_ATOMS,
    PROTEIN_BACKBONE_BONDS,
    RNA_BACKBONE_BONDS,
    STANDARD_BOND_LENGTHS,
)
from novadb.constants.elements import (
    COVALENT_RADII,
    ELEMENT_ORDER,
    ELEMENT_TO_ATOM_TYPE,
    ELECTRONEGATIVITIES,
    METALS,
    NUM_ELEMENTS,
    VDW_RADII,
)
from novadb.constants.residues import (
    AA_1_TO_3,
    AA_3_TO_1,
    AMINO_ACIDS_1,
    AMINO_ACIDS_3,
    AROMATIC_AAS,
    CHARGED_AAS,
    CRYSTALLIZATION_AIDS,
    DNA_NUCLEOTIDES,
    DNA_NUCLEOTIDES_1,
    HYDROPHOBIC_AAS,
    MODIFIED_RESIDUE_MAP,
    NUM_TOKEN_TYPES,
    POLAR_AAS,
    RESTYPE_ORDER,
    RNA_NUCLEOTIDES,
    RNA_NUCLEOTIDES_1,
    STANDARD_RESIDUES,
    TOKEN_TYPES,
    UNKNOWN_RESTYPE,
)
from novadb.constants.af3_constants import (
    # Exclusion lists from AF3 Tables
    CRYSTALLIZATION_AIDS as AF3_CRYSTALLIZATION_AIDS,
    LIGAND_EXCLUSION_LIST,
    GLYCAN_CCD_CODES,
    ION_CCD_CODES,
    POSEBUSTERS_COMMON_LIGANDS,
    # Standard residue sets
    STANDARD_AMINO_ACIDS,
    STANDARD_RNA_NUCLEOTIDES,
    STANDARD_DNA_NUCLEOTIDES,
    # Training parameters
    TRAINING_CUTOFF_DATE,
    TEMPLATE_CUTOFF_DATE,
    MAX_RESOLUTION,
    CROP_SIZE_INITIAL,
    CROP_SIZE_FINETUNE_1,
    CROP_SIZE_FINETUNE_2,
    # Clustering
    PROTEIN_CLUSTER_IDENTITY,
    NUCLEIC_CLUSTER_IDENTITY,
    PEPTIDE_LENGTH_THRESHOLD,
    # Sampling weights
    DATASET_WEIGHTS,
    CROPPING_WEIGHTS,
    # Helper functions
    is_crystallization_aid,
    is_excluded_ligand,
    is_glycan,
    is_ion,
    is_standard_residue,
    is_standard_amino_acid,
    is_standard_nucleotide,
    get_clustering_threshold,
    should_filter_for_training,
)

__all__ = [
    # Residues
    "AMINO_ACIDS_1",
    "AMINO_ACIDS_3",
    "AA_1_TO_3",
    "AA_3_TO_1",
    "RNA_NUCLEOTIDES",
    "RNA_NUCLEOTIDES_1",
    "DNA_NUCLEOTIDES",
    "DNA_NUCLEOTIDES_1",
    "STANDARD_RESIDUES",
    "TOKEN_TYPES",
    "RESTYPE_ORDER",
    "NUM_TOKEN_TYPES",
    "UNKNOWN_RESTYPE",
    "MODIFIED_RESIDUE_MAP",
    "CRYSTALLIZATION_AIDS",
    "HYDROPHOBIC_AAS",
    "POLAR_AAS",
    "CHARGED_AAS",
    "AROMATIC_AAS",
    # Atoms
    "RESIDUE_ATOMS",
    "RESIDUE_ATOM_INDEX",
    "PROTEIN_BACKBONE_ATOMS",
    "RNA_BACKBONE_ATOMS",
    "DNA_BACKBONE_ATOMS",
    "PROTEIN_FRAME_ATOMS",
    "RNA_FRAME_ATOMS",
    "DNA_FRAME_ATOMS",
    "RNA_ATOMS",
    "DNA_ATOMS",
    "MAX_PROTEIN_ATOMS",
    "MAX_RNA_ATOMS",
    "MAX_DNA_ATOMS",
    "MAX_ATOMS_PER_TOKEN",
    "CHI_ANGLES_ATOMS",
    "CHI_ANGLES_MASK",
    # Elements
    "ELEMENT_ORDER",
    "NUM_ELEMENTS",
    "ELEMENT_TO_ATOM_TYPE",
    "VDW_RADII",
    "COVALENT_RADII",
    "ELECTRONEGATIVITIES",
    "METALS",
    # Bonds
    "BOND_TYPE_ORDER",
    "NUM_BOND_TYPES",
    "PROTEIN_BACKBONE_BONDS",
    "RNA_BACKBONE_BONDS",
    "DNA_BACKBONE_BONDS",
    "PEPTIDE_BOND_ATOMS",
    "STANDARD_BOND_LENGTHS",
    "BOND_LENGTH_TOLERANCE",
    "COVALENT_BOND_TOLERANCE",
    # AF3 Constants
    "AF3_CRYSTALLIZATION_AIDS",
    "LIGAND_EXCLUSION_LIST",
    "GLYCAN_CCD_CODES",
    "ION_CCD_CODES",
    "POSEBUSTERS_COMMON_LIGANDS",
    "STANDARD_AMINO_ACIDS",
    "STANDARD_RNA_NUCLEOTIDES",
    "STANDARD_DNA_NUCLEOTIDES",
    "TRAINING_CUTOFF_DATE",
    "TEMPLATE_CUTOFF_DATE",
    "MAX_RESOLUTION",
    "CROP_SIZE_INITIAL",
    "CROP_SIZE_FINETUNE_1",
    "CROP_SIZE_FINETUNE_2",
    "PROTEIN_CLUSTER_IDENTITY",
    "NUCLEIC_CLUSTER_IDENTITY",
    "PEPTIDE_LENGTH_THRESHOLD",
    "DATASET_WEIGHTS",
    "CROPPING_WEIGHTS",
    # AF3 Helper functions
    "is_crystallization_aid",
    "is_excluded_ligand",
    "is_glycan",
    "is_ion",
    "is_standard_residue",
    "is_standard_amino_acid",
    "is_standard_nucleotide",
    "get_clustering_threshold",
    "should_filter_for_training",
]
